sonar.host.url=https://sonarcloud.io
sonar.projectKey=aripalo_aws-cdk-github-oidc
sonar.organization=aripalo
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.sources=./src
sonar.tests=./test
sonar.test.inclusions=**/*.test.*